#!/bin/sh
#
# env-setup.sh
#
# command: `source env-setup.sh`

export CACHE_HOST=localhost
echo "CACHE_HOST=$CACHE_HOST"
export CACHE_PORT=6379
echo "CACHE_PORT=$CACHE_PORT"
export CACHE_PASSWORD=
echo "CACHE_PASSWORD=$CACHE_PASSWORD"
export TWITTER_APP_CONSUMER_KEY=
echo "TWITTER_APP_CONSUMER_KEY=$TWITTER_APP_CONSUMER_KEY"
export TWITTER_APP_CONSUMER_SECRET=
echo "TWITTER_APP_CONSUMER_SECRET=$TWITTER_APP_CONSUMER_SECRET"
export TWITTER_USER_ACCESS_TOKEN=
echo "TWITTER_USER_ACCESS_TOKEN=$TWITTER_USER_ACCESS_TOKEN"
export TWITTER_USER_ACCESS_SECRET=
echo "TWITTER_USER_ACCESS_SECRET=$TWITTER_USER_ACCESS_SECRET"

echo "env set up successfully"
